const wordList = [
  { word: "cat", hint: "A small, fluffy animal that says 'meow.'" },
  { word: "car", hint: "A vehicle that moves on wheels." },
  { word: "ball", hint: "A round object that you can play with." },
  { word: "duck", hint: "A bird that quacks and is often found in ponds." },
  { word: "book", hint: "An item with pages that you can read." },
  { word: "flower", hint: "A colorful plant with petals." },
  { word: "apple", hint: "A red or green fruit that is crunchy and sweet." },
  { word: "bed", hint: "A piece of furniture for sleeping." },
  { word: "fish", hint: "An animal that lives in water and swims." },
  {
    word: "moon",
    hint: "The natural satellite of Earth that lights up the night sky.",
  },
  { word: "train", hint: "A long vehicle that travels on tracks." },
  { word: "tree", hint: "A tall plant with branches and leaves." },
  { word: "sun", hint: "The bright, hot ball of fire in the sky." },
  { word: "house", hint: "A place where people live." },
  { word: "rainbow", hint: "A colorful arc in the sky after rain." },
  { word: "star", hint: "A twinkling point of light in the night sky." },
  { word: "bear", hint: "A large, furry mammal found in the wild." },
  { word: "shoe", hint: "Footwear that you wear on your feet." },
  { word: "cake", hint: "A sweet dessert often served on special occasions." },
  { word: "chair", hint: "A piece of furniture for sitting on." },
];
